# Generated by Django 4.1.5 on 2023-01-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0002_alter_yoga_studio_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yoga',
            old_name='class_hour',
            new_name='class_end_hour',
        ),
        migrations.AddField(
            model_name='yoga',
            name='class_start_hour',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
