# Generated by Django 4.1.5 on 2023-01-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_logins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logins',
            name='no_of_logins',
            field=models.IntegerField(),
        ),
    ]
