# Generated by Django 4.1.5 on 2023-02-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yoga',
            old_name='class_hour',
            new_name='class_start_hour',
        ),
        migrations.AddField(
            model_name='yoga',
            name='class_end_hour',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='yoga',
            name='studio_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='studio_logo',
            field=models.CharField(max_length=200),
        ),
    ]
