# Generated by Django 4.1.5 on 2023-01-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0003_rename_class_hour_yoga_class_end_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoga',
            name='class_end_hour',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
