# Generated by Django 4.1.5 on 2023-02-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0004_alter_yoga_class_end_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoga',
            name='studio_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
