# Generated by Django 4.1.5 on 2023-02-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0005_yoga_studio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoga',
            name='studio_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
